apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://wallet-prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "5s" 
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: prometheus
