spring:
  application:
    name: recargapay-wallet-api
  
  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # Redis Configuration for Distributed Caching
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes default TTL
      cache-null-values: false

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_versioned_data: false
        event:
          merge:
            entity_copy_observer: allow
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    placeholder-replacement: true
    schemas: public
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  
  # JWT secret manually used via JwtDecoderConfig for local/dev environment
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}

# Server configuration
server:
  port: ${SERVER_PORT}

# SpringDoc settings for OpenAPI documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  cache:
    disabled: true
  show-actuator: true
  packages-to-scan: com.recargapay.wallet.adapter.controllers
  paths-to-match: /api/**

# Application Configuration
app:
  # User configuration
  user:
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  
  # Cache configuration
  cache:
    version: ${APP_CACHE_VERSION}
    ttl:
      # TTL values in minutes following financial industry standards
      default: ${CACHE_TTL_DEFAULT_MINUTES}           # Conservative default: 2 minutes
      wallet-list: ${CACHE_TTL_WALLET_LIST_MINUTES}   # Wallet collection: 3 minutes  
      wallet-single: ${CACHE_TTL_WALLET_SINGLE_MINUTES} # Individual wallet: 1 minute
      wallet-balance: ${CACHE_TTL_WALLET_BALANCE_SECONDS} # Critical financial data: 30 seconds
      wallet-transactions: ${CACHE_TTL_WALLET_TRANSACTIONS_MINUTES} # Historical data: 10 minutes
      user-profile: ${CACHE_TTL_USER_PROFILE_MINUTES} # User data: 15 minutes

# OpenTelemetry Configuration
otel:
  sdk:
    disabled: true  # Disable OpenTelemetry SDK auto-configuration
  spring:
    enabled: false  # Disable Spring integration auto-configuration
    webmvc:
      enabled: false # Disable automatic WebMVC instrumentation since we have our own TraceContextFilter
  service:
    name: recargapay-wallet-api
    version: 1.0.0
  resource:
    attributes:
      service.name: recargapay-wallet-api
      service.version: 1.0.0
  # Removed OTLP exporter configuration to prevent connection errors
  propagators: tracecontext,baggage
  metrics:
    exporter: none
  logs:
    exporter: none

# Logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.application.name:-wallet-api}] [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.recargapay.wallet: DEBUG
    org:
      springframework:
        web:
          servlet:
            resource:
              ResourceHttpRequestHandler: WARN
    # Reduzir ruído de logs
    org.springframework.web.servlet.PageNotFound: ERROR

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
