# Actuator and Prometheus configuration
# All comments and documentation are in English as per project standard

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db,diskSpace,ping
        liveness:
          include: ping
      show-components: always
      status:
        http-mapping:
          down: 503
          out-of-service: 503
          unknown: 500
    prometheus:
      enabled: true
    loggers:
      enabled: true
  metrics:
    enable:
      all: true
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        all: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
    tags:
      application: ${spring.application.name}

# Custom metrics configuration
wallet:
  metrics:
    enabled: true
    default-currency: BRL

# Logging configuration for observability
logging:
  level:
    root: INFO
    com.recargapay.wallet: INFO
    org.springframework.web: INFO
    org.springframework.transaction: INFO
    org.springframework.orm.jpa: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n"
  file:
    name: logs/wallet-api.log
    max-size: 10MB
    max-history: 10
    total-size-cap: 100MB
