# Docker profile configuration
# All documentation in English as per project standard

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/walletdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate

# Actuator configuration optimized for containers
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
