# Tempo configuration for distributed tracing

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces  # Alterado de /tmp/tempo/traces para outro diretório

compactor:
  compaction:
    block_retention: 48h
