apiVersion: 1

groups:
  - orgId: 1
    name: 'Wallet API Alerts'
    folder: 'RecargaPay'
    interval: 1m
    rules:
      - uid: wallet_error_rate
        title: 'High Error Rate'
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              editorMode: code
              expr: sum(count_over_time({job="wallet-api"} |= "ERROR" [5m]))
              legendFormat: "ERROR"
              queryType: range
              refId: A
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              editorMode: code
              expr: sum(count_over_time({job="wallet-api"} [5m]))
              legendFormat: "TOTAL"
              queryType: range
              refId: B
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                      - B
                  reducer:
                    params: []
                    type: divide
                  type: query
              refId: C
              type: math
              expression: A/B > 0.1
        dashboardUid: logs001
        panelId: 1
        noDataState: OK
        execErrState: OK
        for: 5m
        annotations:
          description: 'Error rate is high (>10%) for the Wallet API'
          summary: 'High Error Rate Alert'
        labels:
          severity: warning
          category: logs
          service: wallet-api
